apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poi
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: registryyel3358.azurecr.io/tripinsights/poi:1.0
        name: poi
        resources: 
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: SQL_SERVER
          value: "sqlserveryel3358.database.windows.net"
        - name: SQL_USER
          value: "sqladminyEl3358"
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql.password
              key: SQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: poi          