apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: secret1
    type: Opaque
    data: 
    - objectName: secretalias                    # name of the mounted content to sync. this could be the object name or object alias 
      key: secret1
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: 852a8c51-935c-4e62-a9a9-7c9d7bb39a5b # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "tripinsightsRoboClippyKV"
    objects: |
      array:
        - |
          objectName: secret1              
          objectType: secret
          objectAlias: secretalias
          objectVersion: ""
    tenantId: "0f0ca538-b188-4913-b176-6648ed46938f"
---
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline
spec:
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    command:
      - "/bin/sleep"
      - "10000"
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret1
            key: secret1
